services:
  flame:
    image: pawelmalak/flame:latest
    restart: unless-stopped
    profiles:
      - all
      - debug
      - internal
      - flame
    volumes:
      - flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional but required for Docker integration
    environment:
      - TZ
      - PUID
      - GUID
      - PASSWORD=${ADMIN_PASSWORD:?}
    labels:
      - traefik.enable=true
      - traefik.http.routers.flame.rule=Host(`flame.${DOMAIN:?}`)
      - traefik.http.routers.flame.entrypoints=https
      - traefik.http.routers.flame.tls=true
      - traefik.http.routers.flame.tls.certresolver=sslresolver

volumes:
  flame-data: