services:
  pve-exporter:
    init: true
    image: prompve/prometheus-pve-exporter
    restart: unless-stopped
    profiles:
      - all 
      - grafana
      - pve
    volumes:
      - 'pve-exporter-config:/etc/prometheus'

  adguard-exporter:
    image: 'ghcr.io/henrywhitaker3/adguard-exporter:latest'
    restart: unless-stopped
    profiles:
      - all 
      - grafana
      - adguard
    environment:
      - INTERVAL=15s
      - ADGUARD_USERNAMES=${ADMIN_USER:?}
      - ADGUARD_PASSWORDS=${ADMIN_PASSWORD:?}
      - ADGUARD_SERVERS=https://adguard.littlevibe.net

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.3
    restart: unless-stopped
    command: ["sonarr"]
    ports:
      - "9707:9707"
    depends_on:
      - sonarr
    profiles:
      - all
      - arr
    environment:
      PORT: 9707
      URL: "http://sonarr:8989"
      APIKEY: ${SONARR_API_KEY:?}

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.3
    restart: unless-stopped
    command: ["radarr"]
    ports:
      - "9708:9708"
    depends_on:
      - radarr
    profiles:
      - all
      - arr
    environment:
      PORT: 9708
      URL: "http://radarr:7878" 
      APIKEY: ${RADARR_API_KEY:?}

  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.3
    restart: unless-stopped
    command: ["prowlarr"]
    ports:
     - "9710:9710"
    depends_on:
      - prowlarr
    profiles:
      - all
      - arr
    environment:
      PORT: 9710
      URL: "http://prowlarr:9696"
      APIKEY: ${PROWLARR_API_KEY:?}
      PROWLARR_BACKFILL: true # optional
      PROWLARR_BACKFILL_SINCE_DATE: "2023-03-01" # optional

  sabnzbd-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.5.3
    restart: unless-stopped
    command: ["sabnzbd"]
    depends_on:
      - sabnzbd
    profiles:
      - all
      - arr
    ports:
     - "9711:9711"
    environment:
      PORT: 9711
      URL: "http://sabnzbd:8080"
      APIKEY: ${SABNZBD_API_KEY:?}
  
  sabnzbd-exporter-demo:
    image:  msroest/sabnzbd_exporter
    restart: unless-stopped
    command: 
      - \
    depends_on:
      - sabnzbd
    profiles:
      - all
      - arr
    environment:
      - SABNZBD_APIKEYS=${SABNZBD_API_KEY:?}
      - 'SABNZBD_BASEURLS=http://sabnzbd:8080/sabnzbd'

volumes:
  pve-exporter-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACKS_DIR:?}/grafana/pve-exporter
