services:
  portainer:
    image: portainer/portainer-ce:2.0.0
    profiles:
      - all
      - internal
      - portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      # Web UI
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN:?}`)
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=sslresolver
      
      - flame.type=application
      - flame.name=portainer
      - flame.url=https://portainer.${DOMAIN:?}
      - flame.icon=view-portainerboard

volumes:
  portainer-data:
