global:
  scrape_timeout: 10s
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: 
          - alertmanager:9093

scrape_configs:
  - job_name: littlevibe
    metrics_path: /metrics
    honor_timestamps: true
    scheme: http
    static_configs:
      - targets:
        - pve:9100
        - pve-prod-1:9100
        - pve-ct-adguard:9100
        - pve-ct-ansible:9100
        - pve-vm-omv:9100
        - host.docker.internal:9100 # pve-vm-docker:9100
        - nvidia-prod-1:9100
        - pve-ct-nvidia:9100
  
  - job_name: 'windows'
    static_configs:
      - targets: 
        - 'gvgameos:9182'

  - job_name: 'nvidia-dcmg'
    static_configs:
      - targets: 
        - 'nvidia-prod-1:9400'
        - 'pve-ct-nvidia:9400'

  - job_name: 'nvidia'
    static_configs:
      - targets: 
        - 'nvidia-prod-1:9835'
        - 'pve-ct-nvidia:9835'

  - job_name: macos
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - gvmacos:9100

  - job_name: cadvisor
    static_configs:
      - targets: 
          - 'cadvisor:8080'
          - 'nvidia-prod-1:8080'
          - 'pve-ct-nvidia:8080'
        labels:
          container: 'cadvisor'

  - job_name: alertmanager
    static_configs:
      - targets: 
          - 'alertmanager:9093'
        labels:
          container: 'alertmanager'

  - job_name: 'adguard'
    static_configs:
      - targets: 
        - 'adguard-exporter:9618'

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.1.1 # Proxmox VE node.
        # - 192.168.1.20 # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221  # PVE exporter.

  - job_name: 'traefik'
    static_configs:
      - targets: 
        - 'host.docker.internal:8082' # - 'traefik:8082'

  - job_name: 'arr'
    static_configs:
      - targets: 
        - 'sonarr-exporter:9707'
        - 'radarr-exporter:9708'
        - 'prowlarr-exporter:9710'
        - 'sabnzbd-exporter:9711'
        - 'sabnzbd-exporter-demo:9387'
