services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    profiles:
      - all
      - debug
      - internal
      - dash
    volumes:
      - dash-host:/mnt/host:ro
    environment:
      - DASHDOT_SHOW_DASH_VERSION=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=littlevibe
      - DASHDOT_WIDGET_LIST=os,cpu,storage,ram,network
      - DASHDOT_ACCEPT_OOKLA_EULA=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.dash.rule=Host(`dash.${DOMAIN:?}`)
      - traefik.http.routers.dash.entrypoints=https
      - traefik.http.routers.dash.tls=true
      - traefik.http.routers.dash.tls.certresolver=sslresolver
      - flame.type=application
      - flame.name=Dash
      - flame.url=https://dash.${DOMAIN:?}
      - flame.icon=view-dashboard

volumes:
  dash-host:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /
