services:
  semaphore-db:
    restart: unless-stopped
    image: postgres:14
    profiles:
      - all
      - service
      - semaphore
    environment:
     POSTGRES_USER: semaphore
     POSTGRES_PASSWORD: semaphore
     POSTGRES_DB: semaphore
    volumes: 
     - semaphore-db-data:/var/lib/postgresql/data

  semaphore:
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    profiles:
      - all
      - service
      - semaphore
    depends_on:
      - semaphore-db
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: semaphore-db
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD:?}
      SEMAPHORE_ADMIN_NAME: ${ADMIN_USER}
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_USER:?}@${DOMAIN:?}
      SEMAPHORE_ADMIN: ${ADMIN_USER:?}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes' 
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
    labels:
      - traefik.enable=true
      - traefik.http.routers.semaphore.rule=Host(`semaphore.${DOMAIN:?}`)
      - traefik.http.routers.semaphore.entrypoints=https
      - traefik.http.routers.semaphore.tls=true
      - traefik.http.routers.semaphore.tls.certresolver=sslresolver
      - traefik.http.services.semaphore.loadbalancer.server.port=3000
      - flame.type=application
      - flame.name=semaphore
      - flame.url=https://semaphore.${DOMAIN:?}
      - flame.icon=view-semaphoreboard

volumes:
  semaphore-db-data: